name: Tests

on: [push, workflow_dispatch, pull_request]

jobs:
  # Run unittest tests.
  unittest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install Workloads
        run: dotnet workload restore 
      - name: Build and Run Tests
        run: dotnet test