name: Tests

on: [push, workflow_dispatch, pull_request]

jobs:
  # Run unittest tests.
  unittest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 7.0
        uses: actions/setup-dotnet@v3
      - name: Display dotnet version
        run: dotnet --version
      - name: Install Workloads
        run: dotnet workload restore 
      - name: Build and Run Tests
        run: dotnet test